apiVersion: v1
kind: Service
metadata:
    name: haskellers
    labels:
        name: haskellers
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 3006
      protocol: TCP
    selector:
        name: haskellers
